services:
  # --- INFRASTRUCTURE: REVERSE PROXY (GATEKEEPER) ---
  nginx:
    build:
      context: ./infra/nginx
    image: arsneonci/erp-nginx:latest
    container_name: erp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - gateway-service
    networks:
      - erp-network

  # --- FRONTEND APPLICATIONS ---
  
  # 1. ERP Portal (React Vite - Internal postgres)
  erp-portal:
    build:
      context: ./apps/frontend/erp-portal
    image: arsneonci/erp-portal:latest
    container_name: erp-portal
    expose:
      - "80" # Chạy Nginx nội bộ container
    networks:
      - erp-network

  # 2. Ecommerce Store (NextJS - Customer Facing)
  ecommerce-store:
    build:
      context: ./apps/frontend/ecommerce-store
    image: arsneonci/ecommerce-store:latest
    container_name: ecommerce-store
    expose:
      - "3000" # Chạy Node server
    environment:
      - NEXT_PUBLIC_API_URL=https://ldgcompany.local/api # Gọi API qua Nginx chính
    networks:
      - erp-network

  # --- API GATEWAY (JAVA) ---
  gateway-service:
    build: 
      context: ./apps/gateway
    env_file:
      - .env
    image: arsneonci/gateway-service:latest
    container_name: gateway-service
    expose:
      - "8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - IDENTITY_SERVICE_URL=http://identity-service:8080
      - HRM_SERVICE_URL=http://hrm-service:8080
      - SUPPLY_CHAIN_URL=http://supply-chain-service:8080
      - SALES_SERVICE_URL=http://sales-service:8080
      - ACCOUNTING_SERVICE_URL=http://accounting-service:8080
      - AI_SERVICE_URL=http://ai-service:8000
    depends_on:
      - identity-service
      - hrm-service
#      - supply-chain-service
#      - ai-service
#      - sales-service
#      - accounting-service
    networks:
      - erp-network

  # --- MICROSERVICES & DATABASES ---

  # 1. Identity Service (Java)
  identity-service:
    build: 
      context: ./apps/identity
    env_file:
    - .env
    image: arsneonci/identity-service:latest
    container_name: identity-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-identity:5432/identity_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=DEADlift12Hard
      - JWT_SECRET=${JWT_SECRET}
      - SERVER_SERVLET_CONTEXT_PATH=/identity
      - SPRING_GRAPHQL_PATH=/graphql
      - SERVER_PORT=8080
    depends_on:
      - db-identity
    networks:
      - erp-network

  db-identity:
    image: postgres:15-alpine
    container_name: db-identity
    environment:
      - POSTGRES_DB=identity_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=DEADlift12Hard
    volumes:
      - identity-data:/var/lib/postgresql/data
    networks:
      - erp-network

  # 2. HRM Service (Java)
  hrm-service:
    build: 
      context: ./apps/services/hrm
    env_file:
    - .env
    image: arsneonci/hrm-service:latest
    container_name: hrm-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-hrm:5432/hrm_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=DEADlift12Hard
    depends_on:
      - db-hrm
    networks:
      - erp-network

  db-hrm:
    image: postgres:15-alpine
    container_name: db-hrm
    environment:
      - POSTGRES_DB=hrm_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=DEADlift12Hard
    volumes:
      - hrm-data:/var/lib/postgresql/data
    networks:
      - erp-network


networks:
  erp-network:
    driver: bridge

volumes:
  identity-data:
  hrm-data:
