export const ROLES = {
  ADMIN: "ADMIN",

  HR_MANAGER: "HR_MANAGER",
  HR_EMPLOYEE: "HR_EMPLOYEE",

  SCM_MANAGER: "SCM_MANAGER",
  SCM_EMPLOYEE: "SCM_EMPLOYEE",

  SALES_CRM_MANAGER: "SALES_CRM_MANAGER",
  SALES_CRM_EMPLOYEE: "SALES_CRM_EMPLOYEE",

  SUPPLY_CHAIN_MANAGER: "SUPPLY_CHAIN_MANAGER",
  SUPPLY_CHAIN_EMPLOYEE: "SUPPLY_CHAIN_EMPLOYEE",

  FINANCE_ACCOUNTING_MANAGER: "FINANCE_ACCOUNTING_MANAGER",
  FINANCE_ACCOUNTING_EMPLOYEE: "FINANCE_ACCOUNTING_EMPLOYEE",
};