spring:
  application:
    name: identity

  servlet:
    context-path: /identity

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Use 'update' for development, change to 'validate' or 'none' for production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    baseline-on-migrate: true
    check-location: true

server:
  port: ${SERVER_PORT:8080}

graphql:
    path: /identity/graphql    # Đổi endpoint mặc định từ /graphql sang /identity/graphql
    graphiql:
      enabled: true
      path: /identity/graphiql # Đổi luôn trang test GraphiQL

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400