upstream face_ui_upstream {
    # Trỏ vào container face-service cổng 8501 (Streamlit)
    server face-service:8501;
}

server {
    listen 80;
    server_name checkin.local; # Domain mới cho chấm công
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name checkin.local;

    ssl_certificate /etc/nginx/certs/certificate.crt;
    ssl_certificate_key /etc/nginx/certs/private.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://face_ui_upstream;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # --- Cấu hình quan trọng cho Streamlit (WebSocket) ---
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400; # Giữ kết nối lâu cho WebSocket
    }
}