package erp.company.identity.constant;
public enum ERole {
    ADMIN, HR_MANAGER, EMPLOYEE, CUSTOMER, DEPARTMENT_MANAGER,
    PURCHASING_MANAGER, STOREKEEPER, SALES_ADMIN, CFO,
    RECEIVABLE_ACCOUNTANT, PAYABLE_ACCOUNTANT, PAYROLL_ACCOUNTANT
}
