spring:
  application:
    name: accounting
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# --- THÊM PHẦN NÀY ---
jwt:
  signerKey: ${JWT_SECRET}
# ---------------------

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /accounting

logging:
  level:
    root: INFO
    # Thêm log để biết nếu token sai
    org.springframework.security: DEBUG